---
title: "HW9"
author: "Kylie Knudten"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Part 1: Data tidying

```{r}
# import libraries
library(dplyr)
library(tidyverse)
# read in data
av <- read.csv("https://raw.githubusercontent.com/fivethirtyeight/data/master/avengers/avengers.csv",stringsAsFactors = FALSE)

names(av)
av0 = av %>% filter(Name.Alias != "")
av1 = av0 %>% gather(key = time, value = death, c(11, 13, 15, 17, 19)) %>% 
  select(Name.Alias, time, death) %>%
  mutate(time = parse_number(time))
av2 = av0 %>% gather(key = time, value = return, c(12, 14, 16, 18, 20)) %>% 
  select(Name.Alias, time, return) %>%
  mutate(time = parse_number(time))
av.neat = left_join(av1, av2, by = c("Name.Alias", "time"))
av0 = av0 %>% filter(Name.Alias != "Vance Astrovik")
av1 = av0 %>% gather(key = time, value = death, c(11, 13, 15, 17, 19)) %>% 
  select(Name.Alias, time, death) %>%
  mutate(time = parse_number(time))
av2 = av0 %>% gather(key = time, value = return, c(12, 14, 16, 18, 20)) %>% 
  select(Name.Alias, time, return) %>%
  mutate(time = parse_number(time))
av.neat = left_join(av1, av2, by = c("Name.Alias", "time"))
av.neat %>% group_by(time) %>% summarise(total.num = n(),
                                         real.death = sum(death == "YES"), 
                                         fake.death = sum(death == "NO"), 
                                         missing = sum(death == ""))
av.neat %>% filter(time == 1, death == "YES") %>% 
  summarise(total.num = n(),
            real.return = sum(return == "YES"), 
            fake.return = sum(return == "NO"), 
            missing = sum(return == ""))
View(av.neat)
```

